language: java
jdk:
- openjdk8
install:
- mvn dependency:resolve -B
cache:
  directories:
  - "$HOME/.m2/"
script:
- mvn clean package
- mvn sonar:sonar -Dsonar.projectKey=emersonney_fj22-ingressos -Dsonar.organization=emersonney-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=b96fe9e05ffe88857b05865ea3e6aa76f6d724f1
